### ISSUE TITLE
JSON error in Integrator RNN Tutorial

### ISSUE THREAD

**Issue by sternj98** [google-research/computation-thru-dynamics#10]
Hello,

Thank you all for making this, I am very excited about applying these methods. 

I just wanted to report a small error formatting error in the Integrator RNN Tutorial.ipynb file. This file is missing a single comma between lines 55 and 56 that threw a JSON error for me when I first downloaded it. I underline this missing comma below:

`"import sys\n",
    "import time\n" _,_
    "from importlib import reload"
   ]`

Best wishes and thanks again,
Josh

**Comment by youngju-jo** [comment]
Fixed as suggested. Thanks!
