### ISSUE TITLE
LFADS Tutorial running error - unhashable type of init_params

### ISSUE THREAD

**Issue by ecosan327** [google-research/computation-thru-dynamics#13]
I got an error when running LFADS tutorial codes using integrator RNN inputs.

![Screenshot from 2021-09-13 14-33-20](https://user-images.githubusercontent.com/90598608/133034982-200d486f-6fbd-4f2d-8cb6-6a61df7f8bd8.png)

I found "init_params" is a dict type.
But I thought when the code generating "init_params", it's already dict type.

Anyone knows how to fix this?

**Comment by ecosan327** [comment]
> I got an error when running LFADS tutorial codes using integrator RNN inputs.
> 
> ![Screenshot from 2021-09-13 14-33-20](https://user-images.githubusercontent.com/90598608/133034982-200d486f-6fbd-4f2d-8cb6-6a61df7f8bd8.png)
> 
> I found "init_params" is a dict type.
> But I thought when the code generating "init_params", it's already dict type.
> 
> Anyone knows how to fix this?

im using :
cudatoolkit               11.3.1 
cudnn                     8.2.1 
jax                       0.2.20
jaxlib                    0.1.71+cuda111

**Comment by youngju-jo** [comment]
Thanks @ecosan327 -- I had this issue after a jax version update a while ago. One solution is to use FrozenDict of flax (https://github.com/google/flax).

from flax.core.frozen_dict import FrozenDict
lfads_hps = FrozenDict(lfads_hps)

**Comment by ecosan327** [comment]
Thx! In the end I also use this same method to solve the problem =D
